name: Wallester Automation CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create certs directory
        run: mkdir -p certs

      - name: Setup Private Key from Secrets
        # Эта магия берет секрет из GitHub и создает файл private.pem
        run: echo "${{ secrets.RSA_PRIVATE_KEY }}" > certs/private.pem

      - name: Build Docker image
        run: docker build -t wallester-tests .

      - name: Run Tests in Docker
        run: docker run --rm wallester-tests
