name: Wallester Automation CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t wallester-tests .

      - name: Run Tests in Docker
        run: docker run --rm wallester-tests
