name: Wallester Automation CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create certs directory
        run: mkdir -p certs

      - name: Setup Private Key from Secrets
        shell: bash
        run: |
          # Записываем секрет в файл. Кавычки вокруг переменной сохраняют переносы строк.
          echo "${{ secrets.RSA_PRIVATE_KEY }}" > certs/private.pem
          # Устанавливаем права доступа (стандарт для ключей)
          chmod 600 certs/private.pem

      - name: Build Docker image
        run: docker build -t wallester-tests .

      - name: Run Tests in Docker
        run: docker run --rm wallester-tests
